Akanksha1212/C_Programs

basic_programs/Print_ASCII_Value.c

Prints the ASCII value of a character entered by the user.

Added Print_ASCII_Value.c

---

bhaskara.c

This program calculates bhaskara.

Add bhaskara.c

---

basic_programs/2d-matrix.c

4 4 4 4 4 4 4
4 3 3 3 3 3 4
4 3 2 2 2 3 4
4 3 2 1 2 3 4
4 3 2 2 2 3 4
4 3 3 3 3 3 4
4 4 4 4 4 4 4

add matrix console

---

HCF_using_Euclidean_Algorithm

Finding HCF using Recursion
#5

Find HCF of two numbers using Euclidean Algorithm

---

pn.c

issue #5 
i used stdio library and made a function to return number of factors of input number .
then if number of factors is more than 2 then i rejected that number and if equal to 2 then output that number

program to output all prime numbers less than the input numbers

---

sorting/bubble_sort.c
sorting/merge_sort.c

merge_sort.c

---

basic_programs/montecarlopi.c

I'm attaching a commented code which computes an estimation of Pi using the Monte Carlo method.

C Program to estimate Pi using Monte Carlo Method

---

pascals_triangle.c
russian_peasent_algorithm.c

This code can print pascals triangle upto any number of rows

Pascals triangle

---

russian_peasent_algorithm.c

when you are trying to multiply two very big numbers some questions can give you time error
but this algorithm is quite useful

very useful in big multiplication

---

QuadraticEquation.c

I have added a file, In which I take integer coefficients for a second degree polynomial and find their number of roots and solutions in float representation.

added a file for second degree equation

---

number_theory/fibonacci.c

Updated fibonacci.c to calculate for larger terms and have a cleaner output

Updated fibonacci.c to calculate for larger terms

---

sorting/heap_sort.c

contributed

---

changing_base_of_numbers.c

I have added a program to change the base of numbers between 2 to 10

added a program to change base of numbers

---

basic_programs/ring_a_bell.c

A simple c program to make 3 beep sounds like a bell when executed.

Ring A bell in C

---

Ascii Value Finder

This code is for finding the ASCII Value of a character

Create Ascii Value Finder

---

basic_programs/sum_of_digits.c
stack/stack_operations.c

This is a program which calculates the sum of digits of a number

c program to find the sum of digits of a number

---

sorting/radiax.c

The idea of Radix Sort is to do digit by digit sort starting from least significant digit to most significant digit.

Radiax Sort

---

sum_of_first_n_even_nos.c

I have added a basic C program that prints the sum of first n even numbers using recursion.

sum of first n even nos using recursion added

---

number_theory/sterling_algorithm.c

Add Stirling algorithm for power sum calculation for issue #5

added stirling algorithm for power sum calculation

---

sorting/Bubble Sort.c

Easy code for Bubble sort in c program

Create Bubble Sort.c

---

sorting/counting_sort.c

Added counting sort algorithm in sorting folder please have a look

added counting sort

---

conversion/bin to dec/main.c
conversion/bin to hex/main.c
conversion/dec to binary/main.c
conversion/dec to hex/main.c
conversion/dec to octal/main.c
conversion/hex to binary/main.c
conversion/hex to dec/main.c
conversion/octal to decimal/main.c
structure/address.h
structure/employee.h
structure/header.h
structure/main.c
structure/structA.h
structure/structB.h
union/header.h
union/main.c
union/unionA.h
union/unionB.h

added 10 programs to list

---

SelectionOfObject.c

I have added a program to calculate number of ways of selecting r thing for n, using binomial formula nCr , and since for large numbers it is too big number that's why answer will be in form of 1e9+7.

to find number of ways to select r thing from n

---

basic_programs/half_pyramid.c

half_pyramid

---

printing the input.c

this is a c programme to output(on screen and i the same order) the input you have given to the programme. this can be very helpful to learn the concept of the printf and scanf functions in c.

printing the input

---

number_theory/Max and Min of given 10 numbers

added program to find Max and Min of given 10 numbers

Max and Min of given 10 numbers

---

Linked_list/ordered_linked_list.c
stack_using_linked_list/stack_using_linkedlist.c

I implemented stack using linked list and ordered linked list in c

implementation of orderedlinkedlist and stack using linkedlist in c

---

Linked_list/Circular_Double_Linked_List.c
Linked_list/Circular_Linked_List.c

In the Linked List folder Data Structures Circular Linked List & Circular Double Linked List Added

Programs for Data Structures Circular Linked List & Circular Double Linked List Added

---

stack/stack_operations.c

Add an option for "peek" (show the last element without deleting it) in the program for Stack

Add peek to stack.c

---

number_theory/binary_exponentiation.c

Adding binary exponentiation algorithm.

Adding binary exponentiation algorithm.

---

leapyear.c

I have added a cprogram to check whether the year given by user is leap year or not.
First it check whether a year is century year or not and then satisfy condition of leap year that is (divisibility by 4).

Added a Cprogram to check whether a year is leap year or not

---

basic_programs/swap.c

Hi, 
I have added a C program of Swapping values from two variables without taking any third variable. I hope this will be helpful for the beginners. I added this in a new branch called addSwap. Have a look & pull this code.
Thanks & regards
Sayantan

Added swap

---

Calender.c

I have added a Cprogram to find the day of 1st january of a year given by the user.

Added a Cprogram to find the day of 1st january in that year

---

number_theory/sieve.c

Adding sieve algorithm

---

queue/circular_queue.c

added circular queue

---

queue/circular_queue.c
stack/infix_to_postfix.c

Infix to postfix

---

basic_programs/Sum of Squares

C program to calculate the sum of squares of first N natural numbers.

Sum of Squares

---

basic_programs/decimal_to_binary.c

added new code(decimal to binary)

---

basic_programs/factorial_large.c

My code can calculate factorial upto 5000, and I added this code in the basic programs folder.

added code to calculate upto 5000 factorial

---

stack/evalution_of_postfix_expreesion.c

evalution of postfix expression

evalution of postfix expression

---

min_cost_path.c
stack/evalution_of_postfix_expreesion.c

Min cost path

---

Dynamic_programing/min_coins.c
min_cost_path.c
stack/evalution_of_postfix_expreesion.c
stack/two_stacks.c

Two stacks

---

basic_programs/Prime_Printer.c

Prints all the prime numbers within an interval(inclusive).

Prime Printer within a range

---

largefactorials.c

this program is not a usual one as it can compute upto 5100! is nearly 20,000 digits. this range can be easily increased by following the instructions inside the program.

I have added an interesting cprogram for calculating large factorials

---

ind.c

i have c program to count the deepest level of indentation given as input , for example if we give (()()) as input , answer would be 2.

added program to count deepest level of indentation

---

sorting/Bubble Sort.c

I added the option to write the sequence and choose the type of ordination.

Update Bubble Sort.c

---

Matrix_multiplication/Makefile
Matrix_multiplication/matrix_Strassen.c
Matrix_multiplication/matrix_mul.c

I create matrix multiplication.
And implement it using Strassen algorithm.

Create matrix multiplication

---

basic_programs/omang_pattern_alphabets.c

User is asked for the input of the number of rows of half diamond and makes a pattern starting from Z

Diamond pattern starting from Z

---

basic_programs/vishesh_find_e_to_power_x.c

since : e^x = 1 + x + x^2 / 2! + x^3 / 3! + x^4 / 4! + .... + x^n / n!].
At the time of execution, the program will print the message on the console as:
Enter n value : ____
Next, the program should print the message on the console as:
Enter x value :______
and get the answer

program to find out the e^x using functions

---

queue/Queue_using_linkedList.c

Added an implementation of Queues using Linked list

Added an implementation of Queues using Linked list

---

solutions.c

this program solves x^2 + sqrt(x) = c , where is variable given as input by the user

added a program to solve a equation with variable constant

---

strings/Count_Occurence.c

This is my first contribution have a look please.

Added String Program

---

number_theory/Palindrome.c

Created  Palindrome Program in  C

Created  Palindrome Program in  C

---

basic c program

i have added program to find the square root of a number.

Create basic c program

---

socket_programing/TCP/client.c
socket_programing/TCP/server.c

Can be compiled with gcc and run on any OS (tested on linux/unix).

Simple tcp client and server by using C socket programing.

---

Patterns/Full-pyramid.c
Patterns/Pascals-triangle.c

full pyramid added

---

Pattern0

butterfly pattern

---

Dynamic_programing/longest_common_subsequence.c

I added the recursive c language program for finding length of longest common subsequence between two sequences.

Added longest common subsequence (DP)

---

Matrix/Transpose of a matrix.cpp
strings/Finding number of vowels,constants & spaces in a string.cpp

C++ program to find number of vowels, constants, digits and spaces in a string.

String Description

---

Linked_list/merge.c

Merging linked lists

---

Dynamic_programing/knapsack_dynamic.cpp

added knapsack problem using dynamic programming in the corresponding folder

added knapsack problem using dynamic programming

---

array/Finding missing number.c
basic_programs/swapping of two numbers.c

C basic codes added

---

basic c program

included math.h header file to call the function sqrt(). This will reduce the size of code and reduce the time of execution.

optimised the code

---

basic c program

reduced the code, included a header file math.h to call the function sqrt(), which reduced the code, size of program and execution time.

optimized the code

---

diagnolsubtraction.c

A simple c program used to calculate the difference of the sum of diagonals.

Contribution to C programs

---

Nth_root.c

This c program gives the Nth root of a number.

Nth_root_of_a_number

---

strings/split_string.c

Added a C program to split a string given by space.

Added a C program to split a string given by space.

---

ternary_search.cpp

Add ternary_search.cpp

---

strings/string_reversal.c

Added a string reversal  program in C

Added a string reversal  program in C

---

binary_to_decimal.c

C Program to Convert Binary to Decimal

Binary_To_Decimal

---

Searching/fibonaccisearch.c

this is program for fibonacci search

create fibonacci search

---

Searching/interpolation_search.c

Interpolation Search is an improvement over Binary Search for instances, where the values in a sorted array are uniformly distributed.

Added interpolation search program
